'use client';

import { ProjectPage, Media, Row, Chapter } from '@/components/project/ProjectPage';
import { useT } from '@/components/i18n';

export default function Page() {
  const t = useT();
  return (
    <ProjectPage
      title="Hennessy X.O Second Skin"
      subtitle={t('Art génératif & UI, avec OKCC', 'Generative art & UI, with OKCC')}
      meta={{
        year: '2025',
        context: t('OKCC — présenté à VivaTech 2025', 'OKCC — shown at VivaTech 2025'),
        role: t('Visuels 3D, UI de la tablette de vente', '3D visuals, sales tablet UI'),
        tools: 'Figma, Blender, After Effects',
        award: 'Lovie Award — Best Experience Art Direction',
      }}
      intro={t(
        <>
          <p>
            Second Skin est une édition limitée du Hennessy X.O, née d&apos;une collaboration
            avec l&apos;artiste génératif Florian Zumbrunn. Chaque bouteille reçoit une seconde
            peau générée par ses algorithmes, comme un tableau, et porte un numéro de série qui
            la rend unique.
          </p>
          <p>
            Sur ce projet, j&apos;ai conçu les visuels 3D des bouteilles sous Blender ainsi que
            l&apos;UI de la tablette de vente destinée au château, où les visiteurs découvrent
            et personnalisent leur édition.
          </p>
        </>,
        <>
          <p>
            Second Skin is a limited edition of Hennessy X.O, born from a collaboration with
            generative artist Florian Zumbrunn. Each bottle receives a second skin generated by
            his algorithms, like a painting, and carries a serial number that makes it unique.
          </p>
          <p>
            On this project I designed the 3D bottle visuals in Blender and the UI of the sales
            tablet used at the château, where visitors discover and personalise their edition.
          </p>
        </>
      )}
      next={{ href: '/shu-uemura', title: 'Shu Uemura' }}
    >
      <Media src="/hennessy.png" alt={t('Hennessy X.O Second Skin — rendu 3D', 'Hennessy X.O Second Skin — 3D render')} width={3000} height={1688} priority />

      <Chapter title={t('Le parcours tablette', 'The tablet journey')}>
        <p>
          {t(
            'Le visiteur choisit une couleur dominante puis une couleur secondaire, l’œuvre est générée en direct, et il valide sa création avant impression de la seconde peau.',
            'Visitors pick a dominant colour, then a secondary one; the artwork is generated live, and they approve their creation before the second skin is printed.'
          )}
        </p>
      </Chapter>
      <Media src="/hennessy1.png" alt={t('Hennessy — écran d’accueil de la tablette', 'Hennessy — tablet welcome screen')} width={1366} height={1024} />
      <Row cols={2}>
        <Media src="/hennessy2.png" alt={t('Hennessy — choix de la couleur dominante', 'Hennessy — dominant colour')} width={1366} height={1024} />
        <Media src="/hennessy3.png" alt={t('Hennessy — choix de la couleur secondaire', 'Hennessy — secondary colour')} width={1366} height={1024} />
      </Row>
      <Row cols={2}>
        <Media src="/hennessy4.png" alt={t('Hennessy — génération de l’œuvre', 'Hennessy — artwork generation')} width={1366} height={1024} />
        <Media src="/hennessy5.png" alt={t('Hennessy — validation de la création', 'Hennessy — approving the creation')} width={1366} height={1024} />
      </Row>
      <Media src="/hennessy6.png" alt={t('Hennessy — écran de remerciement', 'Hennessy — thank-you screen')} width={1366} height={1024} />
    </ProjectPage>
  );
}
