import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* IvyOra */}
        <link rel="stylesheet" href="https://use.typekit.net/cgb0rtc.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
